mongo:
  image: mongo:2.2.7
  ports:
    - 127.0.0.1:27017:27017
  volumes:
    - /usr/local/var/mongodb
  restart: always

elasticsearch:
  image: elasticsearch:1.4
  ports:
    - 127.0.0.1:9200:9200
    - 127.0.0.1:9300:9300
  volumes:
    - /usr/local/var/elasticsearch/elasticsearch_DomTancredi/
  restart: always

forestation:
  build: ./forestation
  ports:
    - 3000:3000
  links:
    - elasticsearch:elasticsearch
    - mongo:mongo
  restart: always
